$primary = rgb(acc7ff)
$surface = rgb(121317)
$secondary = rgb(bbc6e4)
$error = rgb(ffb4ab)
$tertiary = rgb(eeb2f4)
$surface_lowest = rgb(0d0e12)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
