[mgr]
show_hidden = true
linemode = "size"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
edit_zed = [
	{ run = 'zeditor "$@"', block = false, desc = "Zed" }
]
edit_nvim = [
	{ run = 'nvim "$@"', block = true, desc = "Neovim" }
]

# [open]
# rules = [
# 	{ name = "*.txt", use = [ "edit_zed", "edit_nvim" ] },
# 	{ mime = "text/*", use = [ "edit_zed", "edit_nvim" ] },
# ]
